BEAMS: 2212
BEAM_ENERGIES: 3500
BEAM_SPECTRA: EPA
MI_HANDLER: None
PDF_LIBRARY: None

SCALES: METS{H_T2}{H_T2}
ALPHAS(MZ): 0.1188
ORDER_ALPHAS: 1
ALPHAS: {USE_PDF: 0}

PROCESSES:
  - 22 22 -> 13 -13:
      Order: {QCD: 0, EW: 2}

SELECTORS:
  - [Mass, 13, -13, 10., E_CMS]
  - [PT, 13, 3, E_CMS]
  - [PT, -13, 3, E_CMS]

ANALYSIS: Rivet
RIVET:
  --analyses: CMS_2011_I954992
  USE_HEPMC_SHORT: 1
ANALYSIS_OUTPUT: muon-photoproduction
